/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.41"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation(kotlin("stdlib", "1.3.41"))
    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    compile("io.ktor:ktor-server-netty:1.2.3")

    implementation("io.ktor:ktor-jackson:1.2.3")

    compile("org.jetbrains.exposed:exposed:0.17.1")

    compile("org.slf4j:slf4j-api:1.6.1")

    compile("org.slf4j:slf4j-simple:1.6.1")
}

application {
    // Define the main class for the application
    mainClassName = "wooOOoo.AppKt"
}
